version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:  
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: Set the token to download the sdk
          command: sed -i 's/ADD_TOKEN_HERE/'"$CS_ANDROID_SDK_ENTITLEMENT_TOKEN"'/g' build.gradle.kts

      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug    

workflows:
  android-workflow: 
    jobs:
      - build-and-test:
          context: moonsense-global
